import:
	org.bukkit.Color

on load:
	set {editor::bpm} to 120 if {editor::bpm} is not set
	set {editor::tick} to 0 if {editor::tick} is not set
	set {editor::length} to 1 if {editor::length} is not set
	set {editor::preTime} to 0 if {editor::preTime} is not set

on player drop:
	cancel event

on swap hand items:
	cancel event
	if {editMode} is true:
		if {editor::glowing} is false:
			set {editor::glowing} to true
			play sound "ui.button.click" with pitch 2 to player
			send title "" with subtitle "&7发光: &a开" to player for 0.5 seconds with fade in 0 seconds and fade out 0.5 seconds
		else:
			set {editor::glowing} to false
			play sound "ui.button.click" with pitch 2 to player
			send title "" with subtitle "&7发光: &c关" to player for 0.5 seconds with fade in 0 seconds and fade out 0.5 seconds

function editor(p: player, name: text, diff: text):
	clear metadata value "commandhelper" of {_p}
	{_name} is set
	{_diff} is set
	{_p}'s gamemode is not spectator
	if {editMode} is not set:
		clear {editorSave::*}
		clear {editor::*}
		set {editMode} to true
		set {editor::noteType} to "tap"
		set {editor::face} to "w"
		set {editor::glowing} to false
		set {editor::tick} to 0
		set {editor::preTime} to 0
		set {editor::length} to 4
		set {editor::name} to {_name}
		set {editor::diff} to {_diff}
		delete text displays where [metadata value "combo" of input is set]
		delete text displays where [metadata value "score" of input is set]
		delete text displays where [metadata value "level" of input is set]
		delete text displays where [metadata value "soundinfo" of input is set]
		delete text displays where [metadata value "border" of input is "a", "s" or "d"]
		clear {_p}'s inventory
		set slot 0 of {_p} to a light blue wool named "&b"
		set slot 4 of {_p} to a stick named "&d&l魔杖&e (右键放置，左键删除，Shift对齐网格)"
		set slot 8 of {_p} to a white stained glass named "&b"
		set hotbar slot of {_p} to 4
		playChart({_name}, {_diff}, {_p})
		set {editor::bpm} to {bpm}
		set {editor::offset} to {offset}
		set {editor::author} to {author}
		message "" to {_p}
		message "&8&m一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一" to {_p}
		message "" to {_p}
		message "&6按键操作:" to {_p}
		message "    &3[W]       &7步进一格（按住快进）" to {_p}
		message "    &3[S]       &7后退一格（按住快进）" to {_p}
		message "    &e[SPACE] &7播放" to {_p}
		message "    &7[1]     &l  &7更改音符类型（默认为&bTap&f）" to {_p}
		message "    &7[9]       &7更改判定面（默认为前）" to {_p}
		message "    &7[F]       &7设置音符发光（默认为关）" to {_p}
		message "" to {_p}
		message "&8&m一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一" to {_p}
		message "" to {_p}
		message "&c/save &7导出谱面" to {_p}
		message "&c/editor &7退出编辑模式" to {_p}
		message "" to {_p}
		wait 1 tick
		createEditorHolo()
		addTick({_p}, -1)

command /editor [<text>] [<text>]:
	trigger:
		set {_arg2} to arg-2 parsed as number if arg-2 parsed as number is set
		player's gamemode is not spectator
		if arg-1 is not set:
			{editMode} is set
			clear {editMode}
			clear metadata value "commandhelper" of player
			message "&c离开编辑模式"
			clear player's inventory
			clear {editorSave::*}
			clear {editor::noteType}
			set blocks within location(3, 3, 4, world "world", 0, 0) and location(-3, -3, 4, world "world", 0, 0) to air
			loop all block displays:
				delete loop-entity
			delete text displays where [metadata value "editor" of input is set]
			mainGUI()
		
		else if arg-1 is "bpm":
			{_arg2} is set
			set {editor::bpm} to {_arg2}
		else if arg-1 is "author":
			set {editor::author} to arg-2
		else if arg-1 is "offset":
			{_arg2} is set
			set {editor::offset} to {_arg2}
		else if arg-1 is "pretime":
			{_arg2} is set
			set {editor::preTime} to {_arg2}
		else if arg-1 is "help":
			message ""
			message "&8&m一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一"
			message ""
			message "&6按键操作:"
			message "    &3[W]       &7步进一格（按住快进）"
			message "    &3[S]       &7后退一格（按住快进）"
			message "    &e[SPACE] &7播放"
			message "    &7[1]     &l  &7更改音符类型（默认为&bTap&f）"
			message "    &7[9]       &7更改判定面（默认为前）"
			message "    &7[F]       &7设置音符发光（默认为关）"
			message ""
			message "&8&m一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一"
			message ""
			message "&c/save &7导出谱面"
			message "&c/editor &7退出编辑模式"
			message ""
		else if arg-1 is "regive":
			{editMode} is true
			clear player's inventory
			set slot 0 of player to a light blue wool named "&b"
			set slot 4 of player to a stick named "&d&l魔杖&e (右键放置，左键删除，Shift对齐网格)"
			set slot 8 of player to a white stained glass named "&b"

every 2 ticks:
	if {editMode} is set:
		send action bar "&6BPM: &f%{editor::bpm}%   &7#&f%floor({editor::tick}/{editor::length}) + 1%  &f%mod({editor::tick}, {editor::length})+1%&7/%{editor::length}% &f(%{editor::tick}/{editor::length}*(60/{editor::bpm})+{editor::preTime}%s)   &f共计 %size of {editorSave::type::*}% Notes" to all players

function editplay():
	{editMode} is true
	{-loaded} is set
	if {-editplay} is not set:
		set {-editplay} to true
		if {-loaded}.getMicrosecondPosition() >= {-loaded}.getMicrosecondLength():
			setTick(random element out of all players, 0)
		set {_time} to min({-loaded}.getMicrosecondLength(), max(0, ({editor::tick}/{editor::length}*(60/{editor::bpm})+{editor::preTime}+{editor::offset}/1000)*1000000))
		{-loaded}.setMicrosecondPosition(round({_time}))
		{-loaded}.start()
		send title "&a▶" with subtitle "&a &a" to all players for 0 ticks with fade in 0 ticks and fade out 15 ticks
	else:
		music("pause")
		clear {-editplay}
		send title "&c⏸" with subtitle "&a &a" to all players for 0 ticks with fade in 0 ticks and fade out 15 ticks

every ticks:
	{editMode} is true
	{-editplay} is true
	{-loaded} is set
	set {_tick} to round(({-loaded}.getMicrosecondPosition()-{editor::preTime}*1000000-{editor::offset}*1000)/60000000*{editor::bpm}*{editor::length})
	if {editor::tick} is not {_tick}:
		setTick(random element out of all players, {_tick})

function addTick(p: player, t: number):
	add {_t} to {editor::tick}
	set {editor::tick} to min(32767,max(0,{editor::tick}))
	set {_current} to {editor::tick}/{editor::length}*(60/{editor::bpm})+{editor::preTime}
	loop all block displays:
		metadata value "id" of loop-entity is set
		delete loop-entity
	loop integers from -63 to 63:
		set {_bartemp::%loop-number%} to "&0."
	loop {editorSave::time::*}:
		set {_id} to loop-index
		set {_time} to loop-value
		set {_z} to ({_time} - {_current}) * 20 * {speed::%uuid of {_p}%}
		set {_bartick} to round(({_time} - {_current}) * {editor::bpm} / 60 * 32)
		if all:
			{_bartemp::%{_bartick}%} is "&0."
			{_bartick} is between -63 and 63
		then:
			set {_bartemp::%{_bartick}%} to "&b|" if {editorSave::type::%{_id}%} is "tap"
			set {_bartemp::%{_bartick}%} to "&6|" if {editorSave::type::%{_id}%} is "double"
			set {_bartemp::%{_bartick}%} to "&e|" if {editorSave::type::%{_id}%} is "drag"
			set {_bartemp::%{_bartick}%} to "&d|" if {editorSave::type::%{_id}%} is "flickL"
			set {_bartemp::%{_bartick}%} to "&c|" if {editorSave::type::%{_id}%} is "flickR"
		{_z} >= -1
		{_z} <= 50
		set {_loc} to {editorSave::loc::%loop-index%}
		{_loc}.add(0, 0, {_z})
		summon block display at {_loc}:
			set block data of entity to light_blue_concrete if {editorSave::type::%{_id}%} is "tap"
			set block data of entity to orange_concrete if {editorSave::type::%{_id}%} is "double"
			set block data of entity to yellow_concrete if {editorSave::type::%{_id}%} is "drag"
			set block data of entity to white_concrete if {editorSave::type::%{_id}%} is "hold"
			set block data of entity to magenta_concrete if {editorSave::type::%{_id}%} is "flickL"
			set block data of entity to red_concrete if {editorSave::type::%{_id}%} is "flickR"
			set block data of entity to black stained glass if {editorSave::type::%{_id}%} is "execution"
			set display scale of entity to vector(1,1,1)
			set display scale of entity to vector(1,1,3*{speed::%uuid of {_p}%}) if {editorSave::type::%{_id}%} is "hold"
			set display translation of entity to vector(-0.5,-0.5,0.1)
			set display translation of entity to vector(-0.5,-0.5,0.2) if {editorSave::type::%{_id}%} is "hold"
			set {_displayname} to "&f↑" if {editorSave::face::%{_id}%} is "w"
			set {_displayname} to "&e←" if {editorSave::face::%{_id}%} is "a"
			set {_displayname} to "&6↓" if {editorSave::face::%{_id}%} is "s"
			set {_displayname} to "&c→" if {editorSave::face::%{_id}%} is "d"
			set {_displayname} to "&a+++ %{_displayname}% &a+++" if {editorSave::glowing::%{_id}%} is true
			set display name of entity to {_displayname}
			set metadata value "id" of entity to {_id}
	set {_bartemp::*} to reversed {_bartemp::*}
	set {_bar} to join {_bartemp::*} by ""
	updateBar({_bar})

function setTick(p: player, t: number):
	set {editor::tick} to min(32767,max(0,{_t}))
	set {_current} to {editor::tick}/{editor::length}*(60/{editor::bpm})+{editor::preTime}
	loop all block displays:
		metadata value "id" of loop-entity is set
		add loop-entity to {_entities::*}
	loop integers from -63 to 63:
		set {_bartemp::%loop-number%} to "&0."
	loop {editorSave::time::*}:
		set {_id} to loop-index
		set {_time} to loop-value
		set {_z} to ({_time} - {_current}) * 20 * {speed::%uuid of {_p}%}
		set {_bartick} to round(({_time} - {_current}) * {editor::bpm} / 60 * 32)
		if all:
			{_bartemp::%{_bartick}%} is "&0."
			{_bartick} is between -63 and 63
		then:
			set {_bartemp::%{_bartick}%} to "&b|" if {editorSave::type::%{_id}%} is "tap"
			set {_bartemp::%{_bartick}%} to "&6|" if {editorSave::type::%{_id}%} is "double"
			set {_bartemp::%{_bartick}%} to "&e|" if {editorSave::type::%{_id}%} is "drag"
			set {_bartemp::%{_bartick}%} to "&d|" if {editorSave::type::%{_id}%} is "flickL"
			set {_bartemp::%{_bartick}%} to "&c|" if {editorSave::type::%{_id}%} is "flickR"
		{_z} >= -0.5
		{_z} <= 50
		set {_loc} to {editorSave::loc::%loop-index%}
		{_loc}.add(0, 0, {_z})
		summon block display at {_loc}:
			set block data of entity to light_blue_concrete if {editorSave::type::%{_id}%} is "tap"
			set block data of entity to orange_concrete if {editorSave::type::%{_id}%} is "double"
			set block data of entity to yellow_concrete if {editorSave::type::%{_id}%} is "drag"
			set block data of entity to white_concrete if {editorSave::type::%{_id}%} is "hold"
			set block data of entity to magenta_concrete if {editorSave::type::%{_id}%} is "flickL"
			set block data of entity to red_concrete if {editorSave::type::%{_id}%} is "flickR"
			set block data of entity to black stained glass if {editorSave::type::%{_id}%} is "execution"
			set display scale of entity to vector(1,1,1)
			set display scale of entity to vector(1,1,3*{speed::%uuid of {_p}%}) if {editorSave::type::%{_id}%} is "hold"
			set display translation of entity to vector(-0.5,-0.5,0.1)
			set display translation of entity to vector(-0.5,-0.5,0.2) if {editorSave::type::%{_id}%} is "hold"
			set {_displayname} to "&f↑" if {editorSave::face::%{_id}%} is "w"
			set {_displayname} to "&e←" if {editorSave::face::%{_id}%} is "a"
			set {_displayname} to "&6↓" if {editorSave::face::%{_id}%} is "s"
			set {_displayname} to "&c→" if {editorSave::face::%{_id}%} is "d"
			set {_displayname} to "&a+++ %{_displayname}% &a+++" if {editorSave::glowing::%{_id}%} is true
			set display name of entity to {_displayname}
			set metadata value "id" of entity to {_id}
	set {_bartemp::*} to reversed {_bartemp::*}
	set {_bar} to join {_bartemp::*} by ""
	updateBar({_bar})
	wait 1 tick
	kill {_entities::*}
	
function updateBar(bar2: text):
	set {_totalticks} to round(({-loaded}.getMicrosecondLength() / 1000000 - {editor::offset} / 1000) * {editor::bpm} / 60 * 32)
	set {_bar} to ""
	set {_tick} to round({editor::tick} * 32 / {editor::length})
	loop integers from {_tick}-63 to {_tick}+63:
		if loop-number < 0:
			set {_bar} to "&0.%{_bar}%"
		else if loop-number > {_totalticks}:
			set {_bar} to "&0.%{_bar}%"
		else if loop-number = {_tick}:
			set {_bar} to "&e|%{_bar}%"
		else if mod(loop-number, 32) = 0:
			set {_bar} to "&b,%{_bar}%"
		else if mod(loop-number, 16) = 0:
			set {_bar} to "&f,%{_bar}%"
		else if mod(loop-number, 8) = 0:
			set {_bar} to "&7,%{_bar}%"
		else if mod(loop-number, 4) = 0:
			set {_bar} to "&8.%{_bar}%"
		else:
			set {_bar} to "&0.%{_bar}%"
	set text of {-editorholo::progress} to "%{_bar2}%%nl%%{_bar}%"

every 3 ticks:
	{editMode} is true
	if {-banautotick} is set:
		clear {-banautotick}
	else:
		set {_p} to random element out of all players
		if size of {-keys::*} = 1:
			if {-keys::*} contains "W":
				add 1 to {-wkeyvl}
				if {-wkeyvl} < 6:
					addTick({_p}, 1)
					play sound "block.note_block.hat" with pitch 2 to {_p}
				else:
					addTick({_p}, 4)
					play sound "block.note_block.hat" with pitch 2 to {_p}
			else:
				set {-wkeyvl} to 0

			if {-keys::*} contains "S":
				add 1 to {-skeyvl}
				if {-skeyvl} < 6:
					addTick({_p}, -1)
					play sound "block.note_block.hat" with pitch 1.5 to {_p}
				else:
					addTick({_p}, -4)
					play sound "block.note_block.hat" with pitch 1.5 to {_p}
			else:
				set {-skeyvl} to 0
		else:
			set {-wkeyvl} to 0
			set {-skeyvl} to 0

on tool change:
	{editMode} is set
	cancel event
	player's gamemode is not spectator
	if event-slot is 0:
		play sound "ui.button.click" with pitch 2 to player
		if slot 0 of player is light blue wool named "&b":
			set {editor::noteType} to "double"
			set player's tool to orange wool named "&b"
			send title "" with subtitle "&6Double" to player for 0.5 seconds with fade in 0 seconds and fade out 0.5 seconds
		else if slot 0 of player is orange wool named "&b":
			set {editor::noteType} to "drag"
			set player's tool to yellow wool named "&b"
			send title "" with subtitle "&eDrag" to player for 0.5 seconds with fade in 0 seconds and fade out 0.5 seconds
		else if slot 0 of player is yellow wool named "&b":
			set {editor::noteType} to "hold"
			set player's tool to white wool named "&b"
			send title "" with subtitle "&fHold" to player for 0.5 seconds with fade in 0 seconds and fade out 0.5 seconds
		else if slot 0 of player is white wool named "&b":
			set {editor::noteType} to "flickL"
			set player's tool to magenta wool named "&b"
			send title "" with subtitle "&a← &dFlick" to player for 0.5 seconds with fade in 0 seconds and fade out 0.5 seconds
		else if slot 0 of player is magenta wool named "&b":
			set {editor::noteType} to "flickR"
			set player's tool to red wool named "&b"
			send title "" with subtitle "&cFlick &a→" to player for 0.5 seconds with fade in 0 seconds and fade out 0.5 seconds
		else if slot 0 of player is red wool named "&b":
			set {editor::noteType} to "tap"
			set player's tool to light blue wool named "&b"
			send title "" with subtitle "&bTap" to player for 0.5 seconds with fade in 0 seconds and fade out 0.5 seconds
	else if event-slot is 8:
		play sound "ui.button.click" with pitch 2 to player
		if slot 8 of player is white stained glass named "&b":
			set {editor::face} to "a"
			set player's tool to yellow stained glass named "&b"
			send title "" with subtitle "&7判定面: &e左" to player for 0.5 seconds with fade in 0 seconds and fade out 0.5 seconds
		else if slot 8 of player is yellow stained glass named "&b":
			set {editor::face} to "s"
			set player's tool to orange stained glass named "&b"
			send title "" with subtitle "&7判定面: &6后" to player for 0.5 seconds with fade in 0 seconds and fade out 0.5 seconds
		else if slot 8 of player is orange stained glass named "&b":
			set {editor::face} to "d"
			set player's tool to red stained glass named "&b"
			send title "" with subtitle "&7判定面: &c右" to player for 0.5 seconds with fade in 0 seconds and fade out 0.5 seconds
		else if slot 8 of player is red stained glass named "&b":
			set {editor::face} to "w"
			set player's tool to white stained glass named "&b"
			send title "" with subtitle "&7判定面: &f前" to player for 0.5 seconds with fade in 0 seconds and fade out 0.5 seconds

on right click:
	{editMode} is set
	cancel event
	player's gamemode is not spectator
	if player's tool is stick named "&d&l魔杖&e (右键放置，左键删除，Shift对齐网格)":
		set {_z} to 4
		set {_pz} to z of player
		set {_v} to vector in direction of player
		set {_vx} to x of {_v}
		set {_vy} to y of {_v}
		set {_vz} to z of {_v}
		set {_rate} to abs({_z} - {_pz}) / {_vz}
		set {_vx} to {_vx} * {_rate} + x of player
		if player is sneaking:
			set {_vy} to {_vy} * {_rate} + y of player + 1.4
		else:
			set {_vy} to {_vy} * {_rate} + y of player + 1.6
		set {_vz} to {_vz} * {_rate}
		{_vx} <= 4
		{_vy} <= 4
		{_vx} >= -3
		{_vy} >= -3
		if player is sneaking:
			set {_vx} to round({_vx}*2)/2
			set {_vy} to round({_vy}*2)/2
			set {_loc} to location({_vx}, {_vy}, {_z}, world "world", 0, 0)
		else:
			set {_loc} to location({_vx}, {_vy}, {_z}, world "world", 0, 0)
		send title "" with subtitle "%{_vx} - 0.5% , %{_vy} - 0.5%" to player for 0.5 seconds with fade in 0 seconds and fade out 0.5 seconds
		set {_id} to random uuid
		set {_length} to 3*{speed::%uuid of player%}
		summon block display at {_loc}:
			set block data of entity to light_blue_concrete if {editor::noteType} is "tap"
			set block data of entity to orange_concrete if {editor::noteType} is "double"
			set block data of entity to yellow_concrete if {editor::noteType} is "drag"
			set block data of entity to white_concrete if {editor::noteType} is "hold"
			set block data of entity to magenta_concrete if {editor::noteType} is "flickL"
			set block data of entity to red_concrete if {editor::noteType} is "flickR"
			set display scale of entity to vector(1,1,1)
			set display translation of entity to vector(-0.5,-0.5,0.1)
			set display scale of entity to vector(1,1,{_length}) if {editor::noteType} is "hold"
			set display translation of entity to vector(-0.5,-0.5,0.2) if {editor::noteType} is "hold"
			set {_displayname} to "&f↑" if {editor::face} is "w"
			set {_displayname} to "&e←" if {editor::face} is "a"
			set {_displayname} to "&6↓" if {editor::face} is "s"
			set {_displayname} to "&c→" if {editor::face} is "d"
			set {_displayname} to "&a+++ %{_displayname}% &a+++" if {editor::glowing} is true
			set display name of entity to {_displayname}
			set metadata value "id" of entity to {_id}
			set {editorSave::type::%{_id}%} to {editor::noteType}
			set {editorSave::time::%{_id}%} to {editor::tick}/{editor::length}*(60/{editor::bpm})+{editor::preTime}
			set {editorSave::loc::%{_id}%} to {_loc}
			set {editorSave::face::%{_id}%} to {editor::face}
			set {editorSave::turn::%{_id}%} to "left" if {editor::noteType} is "flickL"
			set {editorSave::turn::%{_id}%} to "right" if {editor::noteType} is "flickR"
			set {editorSave::glowing::%{_id}%} to {editor::glowing}
			set {editorSave::tag::%{_id}%} to ""

on left click:
	{editMode} is set
	cancel event
	player's gamemode is not spectator
	if player's tool is stick named "&d&l魔杖&e (右键放置，左键删除，Shift对齐网格)":
		loop all block displays:
			metadata value "isPreview" of loop-entity is true
			set {_cursor} to loop-entity
		{_cursor} is set
		if distance between (nearest block display relative to {_cursor}) and {_cursor} <= 1:
			set {_id} to metadata value "id" of nearest block display relative to {_cursor}
			clear {editorSave::type::%{_id}%}
			clear {editorSave::time::%{_id}%}
			clear {editorSave::loc::%{_id}%}
			clear {editorSave::face::%{_id}%}
			clear {editorSave::turn::%{_id}%}
			clear {editorSave::section::%{_id}%}
			clear {editorSave::glowing::%{_id}%}
			clear {editorSave::tag::%{_id}%}
			delete nearest block display relative to {_cursor}

command /save:
	trigger:
		{editMode} is set
		player's gamemode is not spectator
		{editor::name} is set
		{editor::diff} is set
		send "&a导出谱面中，请勿操作" to player
		set {_path} to "GAME/levels/%{editor::name}%/%{editor::diff}%.chart"
		set {_pathbackup} to "GAME/levels/%{editor::name}%/%{editor::diff}%.chartbackup"
		delete file path {_pathbackup}
		copy file path {_path} to file path {_pathbackup} if file path {_path} is not missing
		delete file path {_path}
		create file path {_path}
		append "level %{editor::level}%" to file path {_path}
		append "author %{editor::author}%" to file path {_path}
		append "bpm %{editor::bpm}%" to file path {_path}
		append "offset %{editor::offset}%" to file path {_path}
		
		clear {-used::*}
		set {_sorted::*} to sorted indices of {editorSave::time::*} in ascending order
		set {_count} to 0
		loop {_sorted::*}:
			add 1 to {_count}
			set {_id} to loop-value
			{-used::%{_id}%} is not set
			set {_x} to x of {editorSave::loc::%{_id}%}
			set {_y} to y of {editorSave::loc::%{_id}%}
			if {editorSave::type::%{_id}%} is "execution":
				set {_gen} to "%round({editorSave::time::%{_id}%}*1000)% %{editorSave::type::%{_id}%}% %{editorSave::section::%{_id}%}%"
			else if {editorSave::type::%{_id}%} is "tap" or "hold" or "drag":
				set {_gen} to "%round({editorSave::time::%{_id}%}*1000)% %{editorSave::type::%{_id}%}% %{editorSave::face::%{_id}%}% %{_x} - 0.5% %{_y} - 0.5% %{editorSave::glowing::%{_id}%}%"
			else if {editorSave::type::%{_id}%} is "flickR" or "flickL":
				set {_tempType1} to "flick"
				set {_gen} to "%round({editorSave::time::%{_id}%}*1000)% %{_tempType1}% %{editorSave::face::%{_id}%}% %{editorSave::turn::%{_id}%}% %{editorSave::glowing::%{_id}%}%"
			else if {editorSave::type::%{_id}%} is "double":
				set {_tempType} to {editorSave::type::%{_id}%}
				set {_tempTime} to {editorSave::time::%{_id}%}
				set {_tempFace} to {editorSave::face::%{_id}%}
				set {_tempGlowing} to {editorSave::glowing::%{_id}%}
				set {_tempTag} to {editorSave::tag::%{_id}%}
				set {_x1} to x of {editorSave::loc::%{_id}%}
				set {_y1} to y of {editorSave::loc::%{_id}%}
				clear {_x2}
				clear {_y2}
				clear {_id2}
				loop indices of {editorSave::type::*}:
					loop-value-2 is not {_id}
					set {_id2} to loop-value-2
					{editorSave::type::%{_id2}%} is "double"
					{editorSave::time::%{_id2}%} - {_tempTime} is between -0.05 and 0.05
					set {_x2} to x of {editorSave::loc::%{_id2}%}
					set {_y2} to y of {editorSave::loc::%{_id2}%}
					set {-used::%{_id2}%} to true
					exit loop
				set {_gen} to "%round({_tempTime}*1000)% %{_tempType}% %{_tempFace}% %{_x1} - 0.5% %{_y1} - 0.5% %{_x2} - 0.5% %{_y2} - 0.5% %{_tempGlowing}%"
			else:
				set {_gen} to "empty"
			
			if {_gen} contains "<none>":
				replace all "<none>" with "&e<none>&c" in {_gen}
				broadcast "&c✘ &c%{_gen}%"
			else:
				{_gen} is not "empty"
				add {_gen} to {_export::*}
			send action bar "&f%{_count}%/%size of {_sorted::*}%  正在导出: &7%{_gen}%"
			wait 1 tick if mod({_count},100) = 0
		
		append {_export::*} to file path {_path}

		send "&a谱面已保存" to player
		send "&7(前往 &fGAME/levels/%{editor::name}%/%{editor::diff}%.chart&7 查看生成结果)" to player
		send "" to player

every ticks:
	{editMode} is true
	kill block displays where [metadata value "isPreview" of input is true]
	{-editplay} is not true
	loop all players:
		loop-player's gamemode is not spectator
		tool of loop-player is stick named "&d&l魔杖&e (右键放置，左键删除，Shift对齐网格)"
		set {_z} to 4
		set {_pz} to z of loop-player
		set {_v} to vector in direction of loop-player
		set {_vx} to x of {_v}
		set {_vy} to y of {_v}
		set {_vz} to z of {_v}
		set {_rate} to abs({_z} - {_pz}) / {_vz}
		set {_vx} to {_vx} * {_rate} + x of loop-player
		if loop-player is sneaking:
			set {_vy} to {_vy} * {_rate} + y of loop-player + 1.4
		else:
			set {_vy} to {_vy} * {_rate} + y of loop-player + 1.6
		set {_vz} to {_vz} * {_rate}
		{_vx} <= 4
		{_vy} <= 4
		{_vx} >= -3
		{_vy} >= -3
		if loop-player is sneaking:
			set blocks within location(2, 2, 4, world "world", 0, 0) and location(-2, -2, 4, world "world", 0, 0) to glass
			set {_vx} to round({_vx}*2)/2
			set {_vy} to round({_vy}*2)/2
		else:
			set blocks within location(2, 2, 4, world "world", 0, 0) and location(-2, -2, 4, world "world", 0, 0) to air
		set {_loc} to location({_vx}, {_vy}, {_z}, world "world", 0, 0)
		summon block display at {_loc}:
			set block data of entity to light_blue_concrete if {editor::noteType} is "tap"
			set block data of entity to orange_concrete if {editor::noteType} is "double"
			set block data of entity to white_concrete if {editor::noteType} is "hold"
			set block data of entity to yellow_concrete if {editor::noteType} is "drag"
			set block data of entity to magenta_concrete if {editor::noteType} is "flickL"
			set block data of entity to red_concrete if {editor::noteType} is "flickR"
			set display scale of entity to vector(1,1,1)
			set display translation of entity to vector(-0.5,-0.5,0.1)
			
			set {_displayname} to "&f↑" if {editor::face} is "w"
			set {_displayname} to "&e←" if {editor::face} is "a"
			set {_displayname} to "&6↓" if {editor::face} is "s"
			set {_displayname} to "&c→" if {editor::face} is "d"
			set {_displayname} to "&a+++ %{_displayname}% &a+++" if {editor::glowing} is true
			set display name of entity to {_displayname}
			set metadata value "isPreview" of entity to true