import:
	org.bukkit.Color

function createEditorHolo():
	delete text displays where [metadata value "editor" of input is set]

	summon text display at location(7, 4, 5, world "world", 135, 0):
		set display translation of entity to vector(0,0,0)
		set text of the entity to "&fLEVEL"
		entity.setBackgroundColor(Color.fromARGB(0,0,0,0))
		set display scale of entity to vector(2,2,0)
		set metadata value "editor" of the entity to "decorate"
		set sky light override of the entity to 0
		set block light override of the entity to 15
	summon text display at location(7, 2.7, 5, world "world", 135, 0):
		set display translation of entity to vector(0,0,0)
		set text of the entity to "&f%{editor::level}%"
		entity.setBackgroundColor(Color.fromARGB(0,0,0,0))
		set display scale of entity to vector(4,4,0)
		set metadata value "editor" of the entity to "level"
		set sky light override of the entity to 0
		set block light override of the entity to 15
		set {-editorholo::%metadata value "editor" of the entity%} to entity

	summon text display at location(7, 1.7, 5, world "world", 135, 0):
		set display translation of entity to vector(0,0,0)
		set text of the entity to "&fDESIGNER"
		entity.setBackgroundColor(Color.fromARGB(0,0,0,0))
		set display scale of entity to vector(2,2,0)
		set metadata value "editor" of the entity to "decorate"
		set sky light override of the entity to 0
		set block light override of the entity to 15
	summon text display at location(7, 0.4, 5, world "world", 135, 0):
		set display translation of entity to vector(-4.7,0,0)
		set text of the entity to "                             %nl%&f%{editor::author}%"
		entity.setBackgroundColor(Color.fromARGB(0,0,0,0))
		set display scale of entity to vector(4,4,0)
		set metadata value "editor" of the entity to "author"
		set sky light override of the entity to 0
		set block light override of the entity to 15
		set text alignment of the last spawned text display to right aligned
		set {-editorholo::%metadata value "editor" of the entity%} to entity

	summon text display at location(7, -0.6, 5, world "world", 135, 0):
		set display translation of entity to vector(0,0,0)
		set text of the entity to "&fOFFSET"
		entity.setBackgroundColor(Color.fromARGB(0,0,0,0))
		set display scale of entity to vector(2,2,0)
		set metadata value "editor" of the entity to "decorate"
		set sky light override of the entity to 0
		set block light override of the entity to 15
	summon text display at location(7, -1.9, 5, world "world", 135, 0):
		set display translation of entity to vector(0,0,0)
		set text of the entity to "&f%{editor::offset}%"
		entity.setBackgroundColor(Color.fromARGB(0,0,0,0))
		set display scale of entity to vector(4,4,0)
		set metadata value "editor" of the entity to "offset"
		set sky light override of the entity to 0
		set block light override of the entity to 15
		set {-editorholo::%metadata value "editor" of the entity%} to entity

	summon text display at location(-5.5, 4, 5, world "world", -135, 0):
		set display translation of entity to vector(0,0,0)
		set text of the entity to "&fBPM"
		entity.setBackgroundColor(Color.fromARGB(0,0,0,0))
		set display scale of entity to vector(2,2,0)
		set metadata value "editor" of the entity to "decorate"
		set sky light override of the entity to 0
		set block light override of the entity to 15
	summon text display at location(-5.5, 2.7, 5, world "world", -135, 0):
		set display translation of entity to vector(0,0,0)
		set text of the entity to "&f%{editor::bpm}%"
		entity.setBackgroundColor(Color.fromARGB(0,0,0,0))
		set display scale of entity to vector(4,4,0)
		set metadata value "editor" of the entity to "bpm"
		set sky light override of the entity to 0
		set block light override of the entity to 15
		set {-editorholo::%metadata value "editor" of the entity%} to entity

	summon text display at location(-5.5, 1.7, 5, world "world", -135, 0):
		set display translation of entity to vector(0,0,0)
		set text of the entity to "&fBEAT"
		entity.setBackgroundColor(Color.fromARGB(0,0,0,0))
		set display scale of entity to vector(2,2,0)
		set metadata value "editor" of the entity to "decorate"
		set sky light override of the entity to 0
		set block light override of the entity to 15
	summon text display at location(-5.5, 0.4, 5, world "world", -135, 0):
		set display translation of entity to vector(-0.8,0.2,-0.5)
		set text of the entity to "&f%floor({editor::tick}/{editor::length}) + 1%"
		entity.setBackgroundColor(Color.fromARGB(0,0,0,0))
		set display scale of entity to vector(4,4,0)
		set metadata value "editor" of the entity to "beat"
		set sky light override of the entity to 0
		set block light override of the entity to 15
		set {-editorholo::%metadata value "editor" of the entity%} to entity
	summon text display at location(-5.5, 0.4, 5, world "world", -135, 0):
		set display translation of entity to vector(0.5,-0.1,0)
		set text of the entity to "&f%floor({editor::tick}/{editor::length}) + 1%"
		entity.setBackgroundColor(Color.fromARGB(0,0,0,0))
		set display scale of entity to vector(3,3,0)
		set metadata value "editor" of the entity to "beat2"
		set sky light override of the entity to 0
		set block light override of the entity to 15
		set {-editorholo::%metadata value "editor" of the entity%} to entity

	summon text display at location(-5.5, -0.6, 5, world "world", -135, 0):
		set display translation of entity to vector(0,0,0)
		set text of the entity to "&fDIV"
		entity.setBackgroundColor(Color.fromARGB(0,0,0,0))
		set display scale of entity to vector(2,2,0)
		set metadata value "editor" of the entity to "decorate"
		set sky light override of the entity to 0
		set block light override of the entity to 15
	summon text display at location(-5.5, -1.9, 5, world "world", -135, 0):
		set display translation of entity to vector(0,0,0)
		set text of the entity to "&f1/%{editor::length}%"
		entity.setBackgroundColor(Color.fromARGB(0,0,0,0))
		set display scale of entity to vector(4,4,0)
		set metadata value "editor" of the entity to "length"
		set sky light override of the entity to 0
		set block light override of the entity to 15
		set {-editorholo::%metadata value "editor" of the entity%} to entity
	
	summon text display at location(9, 0, 11.5, world "world", 135, 0):
		set display translation of entity to vector(0,0,0)
		set right rotation of the entity to axisAngle(-90, vector(0, 0, 1))
		set text of the entity to "&e|"
		set the line width of the entity to 999
		entity.setBackgroundColor(Color.fromARGB(0,0,0,0))
		set display scale of entity to vector(2,2,0)
		set metadata value "editor" of the entity to "decorate"
		set sky light override of the entity to 0
		set block light override of the entity to 15
		set {-editorholo::progress} to entity
	

every ticks:
	{editMode} is true
	set {_p} to random element out of all players
	set {_v} to normalized (vector in direction of {_p})
	set {_loc} to eye location of {_p}
	set {_x} to x of {_v}
	set {_y} to y of {_v}
	set {_z} to z of {_v}
	{_loc}.add({_x}, {_y}-0.2, {_z})
	loop 25 times:
		{_loc}.add({_x}*0.3, {_y}*0.3, {_z}*0.3)
		set {_find::*} to entities in radius 0.8 around {_loc}
		{_find::1} is set
		if metadata value "editor" of {_find::1} is set:
			metadata value "editor" of {_find::1} is not "decorate"
			set {_e} to {_find::1}
			exit loop
	if {_e} is set:
		set {_id} to metadata value "editor" of {_e}
		{_id} is not "decorate"
		set {-editorselected} to {_id}
	else:
		clear {-editorselected}
	
	if {-editorselected} is "level":
		set text of {-editorholo::level} to "&e%{editor::level}%"
	else:
		set text of {-editorholo::level} to "&f%{editor::level}%"

	if metadata value "commandhelper" of {_p} is "editor author":
		set text of {-editorholo::author} to "                             %nl%&e&n请在聊天栏输入"
	else if {-editorselected} is "author":
		set text of {-editorholo::author} to "                             %nl%&f&n%{editor::author}%"
	else:
		set text of {-editorholo::author} to "                             %nl%&f%{editor::author}%"

	if metadata value "commandhelper" of {_p} is "editor offset":
		set display translation of {-editorholo::offset} to vector(-4.7,0,0)
		set text alignment of {-editorholo::offset} to right aligned
		set text of {-editorholo::offset} to "                             %nl%&e&n请在聊天栏输入"
	else:
		set display translation of {-editorholo::offset} to vector(0,0,0)
		set text alignment of {-editorholo::offset} to center aligned
		set text of {-editorholo::offset} to "&f&n%{editor::offset}%" if {-editorselected} is "offset"
		set text of {-editorholo::offset} to "&f%{editor::offset}%" if {-editorselected} is not "offset"

	if metadata value "commandhelper" of {_p} is "editor bpm":
		set display translation of {-editorholo::bpm} to vector(4.7,0,0)
		set text alignment of {-editorholo::bpm} to left aligned
		set text of {-editorholo::bpm} to "                             %nl%&e&n请在聊天栏输入"
	else:
		set display translation of {-editorholo::bpm} to vector(0,0,0)
		set text alignment of {-editorholo::bpm} to center aligned
		set text of {-editorholo::bpm} to "&f&n%{editor::bpm}%" if {-editorselected} is "bpm"
		set text of {-editorholo::bpm} to "&f%{editor::bpm}%" if {-editorselected} is not "bpm"

	set text of {-editorholo::beat} to "&f%floor({editor::tick}/{editor::length}) + 1%"
	set text of {-editorholo::beat2} to "&f%mod({editor::tick}, {editor::length}) + 1%&7/%{editor::length}%"

	if {-editorselected} is "length":
		set text of {-editorholo::length} to "&e1/%{editor::length}%"
	else:
		set text of {-editorholo::length} to "&f1/%{editor::length}%"

on right click:
	{editMode} is true
	if {-editorselected} is "level":
		play sound "ui.button.click" to player
		set {editor::level} to getNextLevel("%{editor::level}%")
	if {-editorselected} is "author":
		play sound "ui.button.click" to player
		if metadata value "commandhelper" of player is "editor author":
			clear metadata value "commandhelper" of player
		else:
			set metadata value "commandhelper" of player to "editor author"
	if {-editorselected} is "offset":
		play sound "ui.button.click" to player
		if metadata value "commandhelper" of player is "editor offset":
			clear metadata value "commandhelper" of player
		else:
			set metadata value "commandhelper" of player to "editor offset"
	if {-editorselected} is "bpm":
		play sound "ui.button.click" to player
		if metadata value "commandhelper" of player is "editor bpm":
			clear metadata value "commandhelper" of player
		else:
			set metadata value "commandhelper" of player to "editor bpm"
	if {-editorselected} is "length":
		play sound "ui.button.click" to player
		set {_past} to {editor::length}
		set {editor::length} to getNextDiv({editor::length})
		set {editor::tick} to round({editor::tick} * {editor::length} / {_past})
		addTick(player, 0)

on left click:
	{editMode} is true
	if {-editorselected} is "level":
		play sound "ui.button.click" to player
		set {editor::level} to getPreviousLevel("%{editor::level}%")
	if {-editorselected} is "length":
		play sound "ui.button.click" to player
		set {_past} to {editor::length}
		set {editor::length} to getPreviousDiv({editor::length})
		set {editor::tick} to round({editor::tick} * {editor::length} / {_past})
		addTick(player, 0)

function getNextLevel(i: text) :: string:
	return switch return {_i}:
		case "1" -> "2"
		case "2" -> "3"
		case "3" -> "4"
		case "4" -> "5"
		case "5" -> "6"
		case "6" -> "7"
		case "7" -> "8"
		case "8" -> "9"
		case "9" -> "10"
		case "10" -> "11"
		case "11" -> "12"
		case "12" -> "13"
		case "13" -> "14"
		case "14" -> "15"
		case "15" -> "15+"
		case "15+" -> "16"
		case "16" -> "16+"
		case "16+" -> "17"
		case "17" -> "17+"
		case "17+" -> "1"
		default -> "1"

function getPreviousLevel(i: text) :: string:
	return switch return {_i}:
		case "17+" -> "17"
		case "17" -> "16+"
		case "16+" -> "16"
		case "16" -> "15+"
		case "15+" -> "15"
		case "15" -> "14"
		case "14" -> "13"
		case "13" -> "12"
		case "12" -> "11"
		case "11" -> "10"
		case "10" -> "9"
		case "9" -> "8"
		case "8" -> "7"
		case "7" -> "6"
		case "6" -> "5"
		case "5" -> "4"
		case "4" -> "3"
		case "3" -> "2"
		case "2" -> "1"
		case "1" -> "17+"
		default -> "1"

function getNextDiv(i: number) :: number:
	return switch return {_i}:
		case 1 -> 2
		case 2 -> 3
		case 3 -> 4
		case 4 -> 6
		case 6 -> 8
		case 8 -> 12
		case 12 -> 16
		case 16 -> 24
		case 24 -> 32
		case 32 -> 1
		default -> 4

function getPreviousDiv(i: number) :: number:
	return switch return {_i}:
		case 32 -> 24
		case 24 -> 16
		case 16 -> 12
		case 12 -> 8
		case 8 -> 6
		case 6 -> 4
		case 4 -> 3
		case 3 -> 2
		case 2 -> 1
		case 1 -> 32
		default -> 4

on chat:
	{editMode} is true
	metadata value "commandhelper" of player is set
	cancel event
	set {_1} to metadata value "commandhelper" of player
	execute player command "%{_1}% %chat message%"
	clear metadata value "commandhelper" of player