function playChart(name: text, diff: text, p: player):
	set {actor} to {_p}
	set {process} to 0
	clear {-readcomplete}
	clear {editorSave::*}
	set {process} to 10
	readchart({_name}, {_diff})
	#读取metadata.txt与提取文件
	set {_tags::*} to content of file path "GAME/levels/%{_name}%/metadata.txt"
	set {song} to {_tags::1}
	set {artist} to {_tags::2}
	set {path} to {_tags::3}
	replace first "曲名=" with "" in {song}
	replace first "曲师=" with "" in {artist}
	replace first "音乐=" with "" in {path}
	set {path} to "GAME/levels/%{_name}%/%{path}%"
	set {_line1} to line 1 of file path "GAME/levels/%{_name}%/%{_diff}%.chart"
	set {_s::*} to {_line1} split at " "
	if {_s::1} is "level":
		set {level} to "&bEasy %{_s::2}%" if {_diff} is "easy"
		set {level} to "&aBasic %{_s::2}%" if {_diff} is "basic"
		set {level} to "&6Hard %{_s::2}%" if {_diff} is "hard"
		set {level} to "&dChallenge %{_s::2}%" if {_diff} is "challenge"
		set {level} to "&7Inferno %{_s::2}%" if {_diff} is "inferno"
	while {process} is set:
		if {-readcomplete} is true:
			set {_ctn} to true
			exit loop
		else:
			wait 1 tick
	clear {-readcomplete}
	{_ctn} is true
	if {editMode} is true:
		clear {process}
		set {_preload} to preload({path})
		if {_preload} is not "加载完毕":
			send "&c音频加载失败: %{_preload}%" to {_p}
	else:
		set {process} to 25
		set {playing} to {_name}
		if {actor} is set:
			start({actor})
		else:
			clear {process}
			quitGame()
	clear {actor} if {editMode} is true

function getRank(score: number) :: text:
	return "&eSSS+" if {_score} >= 1000000
	return "&eSSS" if {_score} is between 999999 and 990000
	return "&eSS" if {_score} is between 989999 and 980000
	return "&eS" if {_score} is between 979999 and 960000
	return "&aAAA" if {_score} is between 959999 and 950000
	return "&aAA" if {_score} is between 949999 and 940000
	return "&aA" if {_score} is between 939999 and 930000
	return "&bBBB" if {_score} is between 929999 and 920000
	return "&bBB" if {_score} is between 919999 and 910000
	return "&bB" if {_score} is between 909999 and 900000
	return "&2C" if {_score} is between 899999 and 850000
	return "&7D" if {_score} <= 849999

###
function deleteScoreGUI(id: text, p: player):
	set metadata value "prepareToDelete" of {_p} to {_id}
	set {_infoGUI} to chest inventory with 5 rows named "清除该曲成绩？"
	loop integers from 0 to 7:
		set slot loop-value of {_infoGUI} to red stained glass pane named ""
	loop integers from 8 to 9:
		set slot loop-value of {_infoGUI} to red stained glass pane named ""
	loop integers from 17 to 18:
		set slot loop-value of {_infoGUI} to red stained glass pane named ""
	loop integers from 26 to 27:
		set slot loop-value of {_infoGUI} to red stained glass pane named ""
	loop integers from 35 to 44:
		set slot loop-value of {_infoGUI} to red stained glass pane named ""
	set slot 20 of {_infoGUI} to lime wool named "&a清除成绩" with lore "&c此操作无法撤销！"
	open {_infoGUI} to {_p}
###

function settingsGUI(p: player):
	set {_infoGUI} to chest inventory with 6 rows named "设置"
	loop integers from 0 to 7:
		set slot loop-value of {_infoGUI} to gray stained glass pane named ""
	loop integers from 8 to 9:
		set slot loop-value of {_infoGUI} to gray stained glass pane named ""
	loop integers from 17 to 18:
		set slot loop-value of {_infoGUI} to gray stained glass pane named ""
	loop integers from 26 to 27:
		set slot loop-value of {_infoGUI} to gray stained glass pane named ""
	loop integers from 35 to 36:
		set slot loop-value of {_infoGUI} to gray stained glass pane named ""
	loop integers from 44 to 52:
		set slot loop-value of {_infoGUI} to gray stained glass pane named ""
	set slot 20 of {_infoGUI} to feather named "&f音符流速: &e%{speed::%uuid of {_p}%}%" with lore "%nl%&7音符每Tick(1/20秒)移动的距离(米)%nl%&7推荐范围: 1~2.5%nl%&f过高或过低的流速会严重影响游戏体验%nl%%nl%&e点击修改"
	set slot 21 of {_infoGUI} to clock named "&f偏移: &e%{offset::%uuid of {_p}%}%ms" with lore "%nl%&7单位: 毫秒(ms)%nl%&7偏移越高，音符生成越滞后，反之提前%nl%&7如果你遇到了音画不同步，请调整此项%nl%&f注意:第一次播放音画不同步属正常现象%nl%%nl%&e点击修改"
	set slot 22 of {_infoGUI} to note block named "&f打击音效: %{hitSound::%uuid of {_p}%}%" with lore "%nl%&7击中音符时播放打击音效%nl%%nl%&e点击开启/关闭"
	set slot 23 of {_infoGUI} to gold block named "&fFull Combo/Perfect指示器: %{indicator::%uuid of {_p}%}%" with lore "%nl%&7将连击数和分数区域%nl%&7根据您的游戏表现显示不同颜色%nl%%nl%&e点击开启/关闭"
	set slot 24 of {_infoGUI} to piston named "&f自动演奏: %{autoPlay::%uuid of {_p}%}%" with lore "%nl%&7自动演奏歌曲，无需操作%nl%&f该模式下游玩成绩无效%nl%%nl%&e点击开启/关闭"
	set slot 29 of {_infoGUI} to redstone named "&f在判定提示中显示偏移: %{showOffset::%uuid of {_p}%}%" with lore "%nl%&7替换打击特效中的Exact/Just字样为%nl%&7音符到达判定面时间与被击打时间的差值%nl%%nl%&e点击开启/关闭"
	set slot 30 of {_infoGUI} to white concrete named "&f小节提示线: %{showLine::%uuid of {_p}%}%" with lore "%nl%&7在轨道两侧生成提示节拍的细线%nl%%nl%&e点击开启/关闭"
	set slot 53 of {_infoGUI} to barrier named "&c关闭"
	set slot 31 of {_infoGUI} to structure block named "&f编辑谱面: %{useEditor::%uuid of {_p}%}%" with lore "%nl%&7使用编辑器打开或创建谱面%nl%%nl%&e点击开启/关闭"
	open {_infoGUI} to {_p}

on inventory click:
	"%current inventory of player%" is "inventory of <none>"
	cancel event
	if name of event-inventory is "设置":
		setSpeedGUI(player) if index of event-slot = 20
		setOffsetGUI(player) if index of event-slot = 21
		setHitSound(player) if index of event-slot = 22
		setIndicator(player) if index of event-slot = 23
		setAutoPlay(player) if index of event-slot = 24
		setShowOffset(player) if index of event-slot = 29
		setLine(player) if index of event-slot = 30
		setEditor(player) if index of event-slot = 31
		close player's inventory if index of event-slot = 53
	if name of event-inventory is "调速":
		settingsGUI(player) if index of event-slot = 53
		remove 0.5 from {speed::%uuid of player%} if index of event-slot = 19
		setSpeedGUI(player) if index of event-slot = 19
		remove 0.1 from {speed::%uuid of player%} if index of event-slot = 20
		setSpeedGUI(player) if index of event-slot = 20
		remove 0.01 from {speed::%uuid of player%} if index of event-slot = 21
		setSpeedGUI(player) if index of event-slot = 21
		add 0.5 to {speed::%uuid of player%} if index of event-slot = 25
		setSpeedGUI(player) if index of event-slot = 25
		add 0.1 to {speed::%uuid of player%} if index of event-slot = 24
		setSpeedGUI(player) if index of event-slot = 24
		add 0.01 to {speed::%uuid of player%} if index of event-slot = 23
		setSpeedGUI(player) if index of event-slot = 23
	if name of event-inventory is "偏移调整":
		settingsGUI(player) if index of event-slot = 53
		remove 50 from {offset::%uuid of player%} if index of event-slot = 19
		setOffsetGUI(player) if index of event-slot = 19
		remove 10 from {offset::%uuid of player%} if index of event-slot = 20
		setOffsetGUI(player) if index of event-slot = 20
		remove 1 from {offset::%uuid of player%} if index of event-slot = 21
		setOffsetGUI(player) if index of event-slot = 21
		add 50 to {offset::%uuid of player%} if index of event-slot = 25
		setOffsetGUI(player) if index of event-slot = 25
		add 10 to {offset::%uuid of player%} if index of event-slot = 24
		setOffsetGUI(player) if index of event-slot = 24
		add 1 to {offset::%uuid of player%} if index of event-slot = 23
		setOffsetGUI(player) if index of event-slot = 23
###
	if name of event-inventory is "清除该曲成绩？":
		set {_id} to metadata value "prepareToDelete" of player
		if index of event-slot = 20:
			clear {best::%uuid of player%::%{_id}%}
			clear metadata value "prepareToDelete" of player
			close player's inventory
			send "&a清除成绩成功" to player
		if index of event-slot = 24:
			close player's inventory
			clear metadata value "prepareToDelete" of player
###

function setSpeedGUI(p: player):
	set {_infoGUI} to chest inventory with 6 rows named "调速"
	loop integers from 45 to 52:
		set slot loop-value of {_infoGUI} to gray stained glass pane named ""
	set slot 53 of {_infoGUI} to comparator named "&a设置" with lore "%nl%&e点击返回"
	set slot 19 of {_infoGUI} to 50 orange stained glass panes named "&6-0.5" with lore "&7当前: %{speed::%uuid of {_p}%}%"
	set slot 20 of {_infoGUI} to 10 orange stained glass panes named "&6-0.1" with lore "&7当前: %{speed::%uuid of {_p}%}%"
	set slot 21 of {_infoGUI} to 1 orange stained glass pane named "&6-0.01" with lore "&7当前: %{speed::%uuid of {_p}%}%"
	set slot 22 of {_infoGUI} to feather named "&f音符流速: &e%{speed::%uuid of {_p}%}%" with lore "%nl%&7音符每Tick(1/20秒)移动的距离(米)%nl%&7推荐范围: 1~2.5%nl%&f过高或过低的流速会严重影响游戏体验"
	set slot 25 of {_infoGUI} to 50 light blue stained glass panes named "&b+0.5" with lore "&7当前: %{speed::%uuid of {_p}%}%"
	set slot 24 of {_infoGUI} to 10 light blue stained glass panes named "&b+0.1" with lore "&7当前: %{speed::%uuid of {_p}%}%"
	set slot 23 of {_infoGUI} to 1 light blue stained glass pane named "&b+0.01" with lore "&7当前: %{speed::%uuid of {_p}%}%"
	open {_infoGUI} to {_p}

function setOffsetGUI(p: player):
	set {_infoGUI} to chest inventory with 6 rows named "偏移调整"
	loop integers from 45 to 52:
		set slot loop-value of {_infoGUI} to gray stained glass pane named ""
	set slot 53 of {_infoGUI} to comparator named "&a设置" with lore "%nl%&e点击返回"
	set slot 19 of {_infoGUI} to 50 orange stained glass panes named "&6-50" with lore "&7当前: %{offset::%uuid of {_p}%}%ms"
	set slot 20 of {_infoGUI} to 10 orange stained glass panes named "&6-10" with lore "&7当前: %{offset::%uuid of {_p}%}%ms"
	set slot 21 of {_infoGUI} to 1 orange stained glass pane named "&6-1" with lore "&7当前: %{offset::%uuid of {_p}%}%ms"
	set slot 22 of {_infoGUI} to clock named "&f偏移: &e%{offset::%uuid of {_p}%}%ms" with lore "%nl%&7单位: 毫秒(ms)%nl%&7偏移越高，音符生成越滞后，反之提前%nl%&7如果你遇到了音画不同步，请调整此项%nl%&f注意:第一次播放音画不同步属正常现象"
	set slot 25 of {_infoGUI} to 50 light blue stained glass panes named "&b+50" with lore "&7当前: %{offset::%uuid of {_p}%}%ms"
	set slot 24 of {_infoGUI} to 10 light blue stained glass panes named "&b+10" with lore "&7当前: %{offset::%uuid of {_p}%}%ms"
	set slot 23 of {_infoGUI} to 1 light blue stained glass pane named "&b+1" with lore "&7当前: %{offset::%uuid of {_p}%}%ms"
	open {_infoGUI} to {_p}

function setHitSound(p: player):
	if {hitSound::%uuid of {_p}%} is "&a开":
		set {hitSound::%uuid of {_p}%} to "&c关"
	else:
		set {hitSound::%uuid of {_p}%} to "&a开"
	settingsGUI({_p})

function setIndicator(p: player):
	if {indicator::%uuid of {_p}%} is "&a开":
		set {indicator::%uuid of {_p}%} to "&c关"
	else:
		set {indicator::%uuid of {_p}%} to "&a开"
	settingsGUI({_p})

function setShowOffset(p: player):
	if {showOffset::%uuid of {_p}%} is "&a开":
		set {showOffset::%uuid of {_p}%} to "&c关"
	else:
		set {showOffset::%uuid of {_p}%} to "&a开"
	settingsGUI({_p})

function setAutoPlay(p: player):
	if {autoPlay::%uuid of {_p}%} is "&a开":
		set {autoPlay::%uuid of {_p}%} to "&c关"
	else:
		set {autoPlay::%uuid of {_p}%} to "&a开"
	settingsGUI({_p})

function setLine(p: player):
	if {showLine::%uuid of {_p}%} is "&a开":
		set {showLine::%uuid of {_p}%} to "&c关"
	else:
		set {showLine::%uuid of {_p}%} to "&a开"
	settingsGUI({_p})

function setEditor(p: player):
	if {useEditor::%uuid of {_p}%} is "&a开":
		set {useEditor::%uuid of {_p}%} to "&c关"
	else:
		set {useEditor::%uuid of {_p}%} to "&a开"
	settingsGUI({_p})