import:
	org.bukkit.Color
	org.bukkit.entity.Display

#======================================================#
#                                                      #
#                   谱面读取部分                       #
#                                                      #
#======================================================#

function registerNote(type: text, time: text, face: text, x: text, y: text, x1: text, y1: text, x2: text, y2: text, turn: text, section: text, glowing: text, tag: text):
	if {editMode} is not true:
		set {_index} to size of indices of {-note::%{_time}%::*} + 1
		set {-note::%{_time}%::%{_index}%::type} to {_type}
		set {-note::%{_time}%::%{_index}%::face} to {_face}
		set {-note::%{_time}%::%{_index}%::x} to {_x} parsed as number
		set {-note::%{_time}%::%{_index}%::y} to {_y} parsed as number
		set {-note::%{_time}%::%{_index}%::x1} to {_x1} parsed as number
		set {-note::%{_time}%::%{_index}%::y1} to {_y1} parsed as number
		set {-note::%{_time}%::%{_index}%::x2} to {_x2} parsed as number
		set {-note::%{_time}%::%{_index}%::y2} to {_y2} parsed as number
		set {-note::%{_time}%::%{_index}%::turn} to {_turn}
		set {-note::%{_time}%::%{_index}%::glowing} to {_glowing}
	else:
		set {_uuid} to random uuid
		if {_type} is not "double":
			set {_loc} to location({_x} parsed as number + 0.5, {_y} parsed as number + 0.5, 4, world "world", 0, 0)
			if {_turn} is "right":
				set {editorSave::type::%{_uuid}%} to "flickR"
			else if {_turn} is "left":
				set {editorSave::type::%{_uuid}%} to "flickL"
			else:
				set {editorSave::type::%{_uuid}%} to {_type}
			set {editorSave::loc::%{_uuid}%} to location(0.5, 0.5, 4, world "world", 0, 0) if {editorSave::type::%{_uuid}%} is "flickR" or "flickL" or "execution"
			set {editorSave::time::%{_uuid}%} to {_time} parsed as number / 1000 if {_time} is set
			set {editorSave::loc::%{_uuid}%} to {_loc} if {_loc} is set
			set {editorSave::face::%{_uuid}%} to {_face} if {_face} is set
			set {editorSave::turn::%{_uuid}%} to {_turn} if {_turn} is set
			set {editorSave::section::%{_uuid}%} to "暂不支持" if {_section} is set
			set {editorSave::glowing::%{_uuid}%} to {_glowing} if {_glowing} is set
			set {editorSave::tag::%{_uuid}%} to {_tag} if {_tag} is set
		else:
			set {_loc1} to location({_x1} parsed as number + 0.5, {_y1} parsed as number + 0.5, 4, world "world", 0, 0)
			set {_loc2} to location({_x2} parsed as number + 0.5, {_y2} parsed as number + 0.5, 4, world "world", 0, 0)
			set {editorSave::type::%{_uuid}%} to {_type} if {_type} is set
			set {editorSave::time::%{_uuid}%} to {_time} parsed as number / 1000 if {_time} is set
			set {editorSave::loc::%{_uuid}%} to {_loc1} if {_loc1} is set
			set {editorSave::face::%{_uuid}%} to {_face} if {_face} is set
			set {editorSave::turn::%{_uuid}%} to {_turn} if {_turn} is set
			set {editorSave::section::%{_uuid}%} to "暂不支持" if {_section} is set
			set {editorSave::glowing::%{_uuid}%} to {_glowing} if {_glowing} is set
			set {editorSave::tag::%{_uuid}%} to {_tag} if {_tag} is set
			set {_uuid2} to random uuid
			set {editorSave::type::%{_uuid2}%} to {_type} if {_type} is set
			set {editorSave::time::%{_uuid2}%} to {_time} parsed as number / 1000 if {_time} is set
			set {editorSave::loc::%{_uuid2}%} to {_loc2} if {_loc2} is set
			set {editorSave::face::%{_uuid2}%} to {_face} if {_face} is set
			set {editorSave::turn::%{_uuid2}%} to {_turn} if {_turn} is set
			set {editorSave::section::%{_uuid2}%} to "暂不支持" if {_section} is set
			set {editorSave::glowing::%{_uuid2}%} to {_glowing} if {_glowing} is set
			set {editorSave::tag::%{_uuid2}%} to {_tag} if {_tag} is set

on load:
	create section with {_id}, {_type}, {_time}, {_face}, {_x}, {_y}, {_x1}, {_y1}, {_x2}, {_y2}, {_turn}, {_section}, {_glowing}, {_tag} stored in {transferChart}:
		add "%{_time}*1000%" to {_args::*}
		add {_type} to {_args::*}
		add {_face} to {_args::*}
		add "%{_x}%" to {_args::*}
		add "%{_y}%" to {_args::*}
		add "%{_x1}%" to {_args::*}
		add "%{_y1}%" to {_args::*}
		add "%{_x2}%" to {_args::*}
		add "%{_y2}%" to {_args::*}
		add {_turn} to {_args::*}
		add {_section} to {_args::*}
		add {_glowing} to {_args::*}
		add {_tag} to {_args::*}
		remove all "empty" from {_args::*}
		remove all "<none>" from {_args::*}
		set {_output} to join {_args::*} by " "
		append {_output} to file path "GAME/migrate/basic.chart"

function readchart(name: text, diff: text):
	file path "GAME/levels/%{_name}%/%{_diff}%.chart" is not missing
	clear {-note::*}
	clear {-noteused::*}
	clear {-beatlinesummoned::*}
	clear {editorSave::*}
	set {_get::*} to content of file path "GAME/levels/%{_name}%/%{_diff}%.chart"
	set {-noteID} to 0
	set {maxNote} to 0
	loop {_get::*}:
		set {_line} to loop-value
		set {_s::*} to {_line} split at " "
		if {_s::1} is "level":
			{editMode} is set
			set {editor::level} to {_s::2}
		if {_s::1} is "bpm":
			{_s::2} parsed as number is set
			set {bpm} to {_s::2} parsed as number
		else if {_s::1} is "offset":
			{_s::2} parsed as number is set
			set {offset} to {_s::2} parsed as number
		else if {_s::1} is "author":
			set {author} to {_s::2}
		else if {_s::1} parsed as number is set:
			add 1 to {-noteID}
			add 1 to {maxNote} if {_s::2} is "tap", "drag" or "flick"
			add 2 to {maxNote} if {_s::2} is "double"
			if {_s::2} is "execution":
				registerNote("%{_s::2}%", "%{_s::1}%", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", "%{_s::3}%", "empty", "empty")
			if {_s::2} is "tap", "drag" or "hold":
				registerNote("%{_s::2}%", "%{_s::1}%", "%{_s::3}%", "%{_s::4}%", "%{_s::5}%", "empty", "empty", "empty", "empty", "empty", "empty", "%{_s::6}%", "%{_s::7}%")
			if {_s::2} is "flick":
				registerNote("%{_s::2}%", "%{_s::1}%", "%{_s::3}%", "empty", "empty", "empty", "empty", "empty", "empty", "%{_s::4}%", "empty", "%{_s::5}%", "%{_s::6}%")
			if {_s::2} is "double":
				registerNote("%{_s::2}%", "%{_s::1}%", "%{_s::3}%", "empty", "empty", "%{_s::4}%", "%{_s::5}%", "%{_s::6}%", "%{_s::7}%", "empty", "empty", "%{_s::8}%", "%{_s::9}%")
	wait 1 tick
	set {-readcomplete} to true

#======================================================#
#                                                      #
#                   旧版转谱部分                       #
#                                                      #
#======================================================#

command /migrate:
	trigger:
		send "谱面转换进行中，完成后可在 CubeRhythm2/GAME/migrate 查看转换结果"
		send "如果输出文件内没有谱面正文，请尝试/sk reload load"
		delete file path "GAME/migrate/basic.chart"
		create file path "GAME/migrate/basic.chart"
		delete file path "GAME/migrate/metadata.txt"
		create file path "GAME/migrate/metadata.txt"
		
		set {_s::*} to {level} split at " "
		if {_s::2} parsed as number is set:
			append "level %{_s::2}%" to file path "GAME/migrate/basic.chart"
		else:
			append "level 0" to file path "GAME/migrate/basic.chart"
		if {author} is set:
			append "author %{author}%" to file path "GAME/migrate/basic.chart"
		else:
			append "author 未知" to file path "GAME/migrate/basic.chart"
		if {bpm} is set:
			append "bpm %{bpm}%" to file path "GAME/migrate/basic.chart"
		else:
			append "bpm 120" to file path "GAME/migrate/basic.chart"
		if {offset} is set:
			append "offset %{offset}%" to file path "GAME/migrate/basic.chart"
		else:
			append "offset 0" to file path "GAME/migrate/basic.chart"
		
		append "曲名=%{song}%" to file path "GAME/migrate/metadata.txt"
		append "曲师=%{artist}%" to file path "GAME/migrate/metadata.txt"
		append "音乐=music.wav" to file path "GAME/migrate/metadata.txt"
		append "封面=bg.jpg" to file path "GAME/migrate/metadata.txt"
		
		loadChart()
		send "谱面转换完成"

function registerChart(id: text, name: text, level: text, artist: text, author: text, length: number, offset: number):
	set {offset} to {_offset}

function setBPM(id: text, bpm: number):
	set {bpm} to {_bpm}

function execution(time: number, section: section):
	set {_type} to "execution"
	run section {transferChart} sync with {noteID}, {_type}, {_time}, "empty", "empty", "empty", "empty", "empty", "empty", "empty", "empty", {_section}, "empty", "empty"

function tap(time: number, face: text, x: number, y: number, glowing: boolean, tag: text):
	set {_type} to "tap"
	run section {transferChart} sync with {noteID}, {_type}, {_time}, {_face}, {_x}, {_y}, "empty", "empty", "empty", "empty", "empty", "empty", {_glowing}, {_tag}

function drag(time: number, face: text, x: number, y: number, glowing: boolean, tag: text):
	set {_type} to "drag"
	run section {transferChart} sync with {noteID}, {_type}, {_time}, {_face}, {_x}, {_y}, "empty", "empty", "empty", "empty", "empty", "empty", {_glowing}, {_tag}

function hold(time: number, face: text, x: number, y: number, glowing: boolean, tag: text):
	set {_type} to "hold"
	run section {transferChart} sync with {noteID}, {_type}, {_time}, {_face}, {_x}, {_y}, "empty", "empty", "empty", "empty", "empty", "empty", {_glowing}, {_tag}

function flick(time: number, face: text, turn: text, glowing: boolean, tag: text):
	set {_type} to "flick"
	run section {transferChart} sync with {noteID}, {_type}, {_time}, {_face}, "empty", "empty", "empty", "empty", "empty", "empty", {_turn}, "empty", {_glowing}, {_tag}

function double(time: number, face: text, x1: number, y1: number, x2: number, y2: number, glowing: boolean, tag: text):
	set {_type} to "double"
	run section {transferChart} sync with {noteID}, {_type}, {_time}, {_face}, "empty", "empty", {_x1}, {_y1}, {_x2}, {_y2}, "empty", "empty", {_glowing}, {_tag}

#======================================================#
#                                                      #
#                   绘制音符部分                       #
#                                                      #
#======================================================#

function delayTranslation(entity: fake entity, v: vector):
	wait 2 ticks
	set {_v0} to fake meta display translation of {_entity}
	add {_v} to {_v0}
	set fake meta display translation of {_entity} to {_v0}
	
function delayKill2(entity: entity, ticks: number):
	set {_t} to "%{_ticks}% ticks" parsed as timespan
	wait {_t}:
		kill {_entity}

function delayKill(entity: fake entity, ticks: number):
	set {_t} to "%{_ticks}% ticks" parsed as timespan
	wait {_t}:
		kill fake entity {_entity}

function drawTap(face: text, x: number, y: number, z: number, glowing: boolean) :: fake entity:
	if {_face} is "w":
		set {_loc1} to location({_x}, {_y}, {_z}, world "world", 0, 0)
	if {_face} is "a":
		set {_loc1} to location({_z}, {_y}, -1*{_x}, world "world", 90, 0)
	if {_face} is "s":
		set {_loc1} to location(-1*{_x}+1, {_y}, -1*{_z}+1, world "world", 180, 0)
	if {_face} is "d":
		set {_loc1} to location(-1*{_z}+1, {_y}, {_x}+1, world "world", 270, 0)

	set {_tv} to vector(0,0,-100*{speed::%uuid of {actor}%}) if {_face} is "w" or "s"
	set {_tv} to vector(0,0,100*{speed::%uuid of {actor}%}) if {_face} is "a" or "d"
	set {_meta} to block display meta data:
		display block data: light_blue_concrete
		display scale: vector(1,1,0.5*{speed::%uuid of {actor}%})
		display billboard: fixed
		display interpolation delay: 0 ticks
		display transform interpolation duration: 100 ticks
	set {_entity} to a new fake block display entity:
		viewers: all players
		location: {_loc1}
		meta: {_meta}
	spawn fake entity {_entity} at {_loc1}
	
	delayTranslation({_entity}, {_tv})
	createAnchor("tap", {_face}, {_loc1})
	
	return {_entity}

function drawHold(face: text, x: number, y: number, z: number, glowing: boolean) :: fake entity:
	if {_face} is "w":
		set {_loc1} to location({_x}, {_y}, {_z}+0.1, world "world", 0, 0)
	if {_face} is "a":
		set {_loc1} to location({_z}+0.1, {_y}, -1*{_x}+1, world "world", -90, 0)
	if {_face} is "s":
		set {_loc1} to location(-1*{_x}+1, {_y}, -1*{_z}+0.9, world "world", 180, 0)
	if {_face} is "d":
		set {_loc1} to location(-1*{_z}+0.9, {_y}, {_x}, world "world", 90, 0)

	set {_tv} to vector(0,0,-100*{speed::%uuid of {actor}%})
	set {_bpm} to {bpm}
	set {_bpm} to 150 if {_bpm} is not a number
	set {_meta} to block display meta data:
		display block data: white_concrete
		display scale: vector(1,1,300/{_bpm}*{speed::%uuid of {actor}%}+1) #每1/4拍是多少ticks？ 60/120bpm=0.5s*20=10ticks/4=2.5ticks
		display billboard: fixed
		display interpolation delay: 0 ticks
		display transform interpolation duration: 100 ticks
	set {_entity} to a new fake block display entity:
		viewers: all players
		location: {_loc1}
		meta: {_meta}
	spawn fake entity {_entity} at {_loc1}
	
	delayTranslation({_entity}, {_tv})
	
	return {_entity}

function drawDrag(face: text, x: number, y: number, z: number, glowing: boolean) :: fake entity:
	if {_face} is "w":
		set {_loc1} to location({_x}, {_y}, {_z}, world "world", 0, 0)
	if {_face} is "a":
		set {_loc1} to location({_z}, {_y}, -1*{_x}, world "world", 90, 0)
	if {_face} is "s":
		set {_loc1} to location(-1*{_x}+1, {_y}, -1*{_z}+1, world "world", 180, 0)
	if {_face} is "d":
		set {_loc1} to location(-1*{_z}+1, {_y}, {_x}+1, world "world", 270, 0)

	set {_tv} to vector(0,0,-100*{speed::%uuid of {actor}%}) if {_face} is "w" or "s"
	set {_tv} to vector(0,0,100*{speed::%uuid of {actor}%}) if {_face} is "a" or "d"
	set {_meta} to block display meta data:
		display block data: yellow_concrete
		display scale: vector(1,1,0.5*{speed::%uuid of {actor}%})
		display billboard: fixed
		display interpolation delay: 0 ticks
		display transform interpolation duration: 100 ticks
	set {_entity} to a new fake block display entity:
		viewers: all players
		location: {_loc1}
		meta: {_meta}
	spawn fake entity {_entity} at {_loc1}
	
	delayTranslation({_entity}, {_tv})
	createAnchor("drag", {_face}, {_loc1})
	
	return {_entity}

function drawFlick(face: text, z: number, turn: text, glowing: boolean) :: objects:
	set {_x} to 0
	set {_y} to 0
	set {_z} to {_z}-0.5
	set {_x2} to -2
	set {_y2} to -2
	if {_face} is "w":
		set {_loc1} to location({_x2}, {_y2}, {_z}, world "world", 0, 0)
		set {_loc3} to location({_x}+0.75, {_y}-2.75, {_z}+0.4, world "world", 180, 0)
	if {_face} is "a":
		set {_loc1} to location({_z}+1, {_y2}, -1*{_x2}-4, world "world", 90, 0)
		set {_loc3} to location({_z}+0.4, {_y}-2.75, -1*{_x}+0.25, world "world", 90, 0)
	if {_face} is "s":
		set {_loc1} to location(-1*{_x2}+1, {_y2}, -1*{_z}+1, world "world", 180, 0)
		set {_loc3} to location(-1*{_x}+0.25, {_y}-2.75, -1*{_z}+0.6, world "world", 0, 0)
	if {_face} is "d":
		set {_loc1} to location(-1*{_z}, {_y2}, {_x2}+5, world "world", 270, 0)
		set {_loc3} to location(-1*{_z}+0.6, {_y}-2.75, {_x}+0.75, world "world", 270, 0)   

	set {_meta} to block display meta data:
		display block data: white_stained_glass_pane[east=true,north=false,south=false,waterlogged=false,west=true]
		display scale: vector(5,5,1)
		display billboard: fixed
		display interpolation delay: 0 ticks
		display transform interpolation duration: 100 ticks
	set {_e1} to a new fake block display entity:
		viewers: all players
		location: {_loc1}
		meta: {_meta}
	set {_entity::1} to {_e1}
	spawn fake entity {_e1} at {_loc1}
	
	if {_turn} is "left":
		set {_meta} to text display meta data:
			display text: "§f←"
			display scale: vector(20,20,0)
			display translation: vector(0,0.75,0)
			display billboard: fixed
			display background color: rgb(0,0,0,0)
			display interpolation delay: 0 ticks
			display transform interpolation duration: 100 ticks
		set {_e2} to a new fake text display entity:
			viewers: all players
			location: {_loc3}
			meta: {_meta}
		set {_entity::2} to {_e2}
		spawn fake entity {_e2} at {_loc3}
	
	if {_turn} is "right":
		set {_meta} to text display meta data:
			display text: "§f→"
			display scale: vector(20,20,0)
			display translation: vector(0,0.75,0)
			display billboard: fixed
			display background color: rgb(0,0,0,0)
			display interpolation delay: 0 ticks
			display transform interpolation duration: 100 ticks
		set {_e3} to a new fake text display entity:
			viewers: all players
			location: {_loc3}
			meta: {_meta}
		set {_entity::2} to {_e3}
		spawn fake entity {_e3} at {_loc3}
	
	if {_e1} is set:
		delayTranslation({_e1}, vector(0,0,-100*{speed::%uuid of {actor}%})) if {_face} is "w" or "s"
		delayTranslation({_e1}, vector(0,0,100*{speed::%uuid of {actor}%})) if {_face} is "a" or "d"
	if {_e2} is set:
		delayTranslation({_e2}, vector(0,0,100*{speed::%uuid of {actor}%})) if {_face} is "w" or "s"
		delayTranslation({_e2}, vector(0,0,100*{speed::%uuid of {actor}%})) if {_face} is "a" or "d"
	if {_e3} is set:
		delayTranslation({_e3}, vector(0,0,100*{speed::%uuid of {actor}%})) if {_face} is "w" or "s"
		delayTranslation({_e3}, vector(0,0,100*{speed::%uuid of {actor}%})) if {_face} is "a" or "d"
	
	return {_entity::*}

function drawDouble(face: text, xa: number, ya: number, za: number, xb: number, yb: number, zb: number, glowing: boolean) :: objects:
	if {_xa} < {_xb}:
		set {_t1} to {_xa}
		set {_t2} to {_ya}
		set {_t3} to {_za}
		set {_xa} to {_xb}
		set {_ya} to {_yb}
		set {_za} to {_zb}
		set {_xb} to {_t1}
		set {_yb} to {_t2}
		set {_zb} to {_t3}
	
	#第一个键
	set {_xa1} to {_xa}+0.5
	set {_ya1} to {_ya}-0.5
	set {_za1} to {_za}+1
	if {_face} is "w":
		set {_loc1} to location({_xa}, {_ya}, {_za}, world "world", 0, 0)
		set {_loc2} to location({_xa1}, {_ya1}, {_za1}, world "world", 0, 0)
	if {_face} is "a":
		remove 1 from {_xa1}
		set {_loc1} to location({_za}, {_ya}, -1*{_xa}, world "world", 90, 0)
		set {_loc2} to location({_za1}, {_ya1}, -1*{_xa1}, world "world", 90, 0)
	if {_face} is "s":
		remove 1 from {_xa1}
		remove 1 from {_za1}
		set {_loc1} to location(-1*{_xa}+1, {_ya}, -1*{_za}+1, world "world", 180, 0)
		set {_loc2} to location(-1*{_xa1}, {_ya1}, -1*{_za1}, world "world", 180, 0)
	if {_face} is "d":
		remove 1 from {_za1}
		set {_loc1} to location(-1*{_za}+1, {_ya}, {_xa}+1, world "world", 270, 0)
		set {_loc2} to location(-1*{_za1}, {_ya1}, {_xa1}, world "world", 270, 0)

	set {_meta} to block display meta data:
		display block data: orange_concrete
		display scale: vector(1,1,0.5*{speed::%uuid of {actor}%})
		display billboard: fixed
		display interpolation delay: 0 ticks
		display transform interpolation duration: 100 ticks
	set {_fake1} to a new fake block display entity:
		viewers: all players
		location: {_loc1}
		meta: {_meta}
	set {_entity::1} to {_fake1}
	spawn fake entity {_fake1} at {_loc1}
	
	#第二个键
	set {_xb1} to {_xb}+0.5
	set {_yb1} to {_yb}-0.5
	set {_zb1} to {_zb}+1
	if {_face} is "w":
		set {_loc3} to location({_xb}, {_yb}, {_zb}, world "world", 0, 0)
		set {_loc4} to location({_xb1}, {_yb1}, {_zb1}, world "world", 0, 0)
	if {_face} is "a":
		remove 1 from {_xb1}
		set {_loc3} to location({_zb}, {_yb}, -1*{_xb}, world "world", 90, 0)
		set {_loc4} to location({_zb1}, {_yb1}, -1*{_xb1}, world "world", 90, 0)
	if {_face} is "s":
		remove 1 from {_xb1}
		remove 1 from {_zb1}
		set {_loc3} to location(-1*{_xb}+1, {_yb}, -1*{_zb}+1, world "world", 180, 0)
		set {_loc4} to location(-1*{_xb1}, {_yb1}, -1*{_zb1}, world "world", 180, 0)
	if {_face} is "d":
		remove 1 from {_zb1}
		set {_loc3} to location(-1*{_zb}+1, {_yb}, {_xb}+1, world "world", 270, 0)
		set {_loc4} to location(-1*{_zb1}, {_yb1}, {_xb1}, world "world", 270, 0)

	set {_meta} to block display meta data:
		display block data: orange_concrete
		display scale: vector(1,1,0.5*{speed::%uuid of {actor}%})
		display billboard: fixed
		display interpolation delay: 0 ticks
		display transform interpolation duration: 100 ticks
	set {_fake2} to a new fake block display entity:
		viewers: all players
		location: {_loc3}
		meta: {_meta}
	set {_entity::2} to {_fake2}
	spawn fake entity {_fake2} at {_loc3}
	
	#连接线
	set {_d1} to distance between {_loc1} and {_loc3}
	set {_d3} to distance between {_loc1} and {_loc3}
	set {_d2} to abs({_xa} - {_xb})
	set {_acos} to acos({_d2}/{_d1}) - 90
	#broadcast "distance: %{_d1}%"
	#broadcast "angle: %{_acos}%"
	if {_ya} <= {_yb}:
		{_loc2}.add(0, 1, -0.8) if {_face} is "w"
		{_loc2}.add(0, 1, 0.8) if {_face} is "s"
		{_loc2}.add(-0.8, 1, 0) if {_face} is "a"
		{_loc2}.add(0.8, 1, 0) if {_face} is "d"

		set {_loc5} to {_loc2}
		set pitch of {_loc5} to {_acos}
		set yaw of {_loc5} to -90 if {_face} is "w"
		set yaw of {_loc5} to -180 if {_face} is "a"
		set yaw of {_loc5} to 90 if {_face} is "s"
		set yaw of {_loc5} to 0 if {_face} is "d"
		
		set {_meta} to block display meta data:
			display block data: white_concrete
			display scale: vector(0.1,{_d3},0.1)
			display billboard: fixed
			display interpolation delay: 0 ticks
			display transform interpolation duration: 100 ticks
		set {_fake3} to a new fake block display entity:
			viewers: all players
			location: {_loc5}
			meta: {_meta}
		set {_entity::3} to {_fake3}
		spawn fake entity {_fake3} at {_loc5}
	
	else:
		{_loc4}.add(0, 1, -0.9) if {_face} is "w"
		{_loc4}.add(0, 1, 0.9) if {_face} is "s"
		{_loc4}.add(-0.9, 1, 0) if {_face} is "a"
		{_loc4}.add(0.9, 1, 0) if {_face} is "d"

		set {_loc6} to {_loc4}
		set pitch of {_loc6} to {_acos}
		set yaw of {_loc6} to 90 if {_face} is "w"
		set yaw of {_loc6} to 0 if {_face} is "a"
		set yaw of {_loc6} to -90 if {_face} is "s"
		set yaw of {_loc6} to -180 if {_face} is "d"
		
		set {_meta} to block display meta data:
			display block data: white_concrete
			display scale: vector(0.1,{_d3},0.1)
			display billboard: fixed
			display interpolation delay: 0 ticks
			display transform interpolation duration: 100 ticks
		set {_fake4} to a new fake block display entity:
			viewers: all players
			location: {_loc6}
			meta: {_meta}
		set {_entity::3} to {_fake4}
		spawn fake entity {_fake4} at {_loc6}
	
	createAnchor("double", {_face}, {_loc1})
	createAnchor("double", {_face}, {_loc3})
	if {_fake1} is set:
		delayTranslation({_fake1}, vector(0,0,-100*{speed::%uuid of {actor}%})) if {_face} is "w" or "s"
		delayTranslation({_fake1}, vector(0,0,100*{speed::%uuid of {actor}%})) if {_face} is "a" or "d"
	if {_fake2} is set:
		delayTranslation({_fake2}, vector(0,0,-100*{speed::%uuid of {actor}%})) if {_face} is "w" or "s"
		delayTranslation({_fake2}, vector(0,0,100*{speed::%uuid of {actor}%})) if {_face} is "a" or "d"
	if {_fake3} is set:
		delayTranslation({_fake3}, vector(100*{speed::%uuid of {actor}%}, 0, 0)) if {_face} is "w" or "s"
		delayTranslation({_fake3}, vector(100*{speed::%uuid of {actor}%}, 0, 0)) if {_face} is "a" or "d"
	if {_fake4} is set:
		delayTranslation({_fake4}, vector(-100*{speed::%uuid of {actor}%}, 0, 0)) if {_face} is "w" or "s"
		delayTranslation({_fake4}, vector(-100*{speed::%uuid of {actor}%}, 0, 0)) if {_face} is "a" or "d"
	
	return {_entity::*}